<?xml version="1.0"?><?target data?>
<Config>
<fferpcore_DataTransformationTable__c Name="Record Type Transformation" fferpcore__Description__c="Converts a static value to a specific record type."/>
<fferpcore_DataTransformationTable__c Name="Employment Status Transformation" fferpcore__Description__c="Converts employment status values."/>
<fferpcore_DataTransformationTable__c Name="Work Calendar Transformation" fferpcore__Description__c="Converts Work Calendar name."/>
</Config>
