<?xml version="1.0"?><?target data?>
<Config>
<FieldReferenceDescribeContext Name="milestone-%" Reference_To__c="Milestone__c"></FieldReferenceDescribeContext>
<FieldReferenceDescribeContext Name="tc-%" Reference_To__c="Timecard__c"></FieldReferenceDescribeContext>
<FieldReferenceDescribeContext Name="assignment-%" Reference_To__c="Assignment__c"></FieldReferenceDescribeContext>
<FieldReferenceDescribeContext Name="resource-request-%" Reference_To__c="Resource_Request__c"></FieldReferenceDescribeContext>
<FieldReferenceDescribeContext Name="project-%" Reference_To__c="Proj__c"></FieldReferenceDescribeContext>
<FieldReferenceDescribeContext Name="skill-rating-%" Reference_To__c="Skill_Rating_Certification__c"></FieldReferenceDescribeContext>
<FieldReferenceDescribeContext Name="resource-%" Reference_To__c="Contact"></FieldReferenceDescribeContext>
</Config>