<?xml version="1.0"?><?target data?>
<Config>
<fferpcore__DataTransformation__c fferpcore__SourceValue1__c="TRUE" fferpcore__TargetValue__c="Resource" fferpcore__DataTransformationTable__c="Record Type Transformation"/>
<fferpcore__DataTransformation__c fferpcore__SourceValue1__c="A" fferpcore__TargetValue__c="Active" fferpcore__DataTransformationTable__c="Employment Status Transformation"/>
<fferpcore__DataTransformation__c fferpcore__SourceValue1__c="T" fferpcore__TargetValue__c="Terminated" fferpcore__DataTransformationTable__c="Employment Status Transformation"/>
</Config>
